//! GPUI running inside a Wasm component, embedded back into a native GPUI application.
//!
//! One crate serves both sides of the boundary:
//!
//! - the **object layer** (this file, always compiled): [`Remote`], [`Receipt`],
//!   [`Ref`], [`Payload`], interfaces/messages/events, and the [`Shared`] home trait —
//!   the typed veneer over the dynamic wire, where everything is
//!   `(target, method: string, payload: bytes + refs)`;
//! - the **object registry** (`registry`, always compiled): one side-blind
//!   implementation of homes and projections that both ends run identically, configured
//!   only with a transport;
//! - the **well-known UI schemas** ([`surface`], always compiled): a host-homed
//!   [`SurfaceApi`] (a place pixels go) and a guest-homed [`ViewApi`] (the thing drawing
//!   there), which is all the protocol knows about views;
//! - the **host runtime** ([`PluginHost`] and friends; native targets only): wasmtime
//!   glue, the [`Surface`] entity that replays display lists, and the transport;
//! - the **guest platform** (wasm32 targets only): a GPUI `Platform` implementation over
//!   the WIT protocol, plus [`Plugin`], [`register_plugin!`], [`open_view`], and the
//!   guest-side transport (`share`, `share_root`, `root`, and friends).
//!
//! See `DESIGN.md` at the repository root for the architecture.

// Lets macro-generated `embedded_gpui::...` paths resolve even when the macro expands
// inside this crate itself.
extern crate self as embedded_gpui;

pub(crate) mod registry;
pub mod schema;
pub mod surface;
pub mod typescript;

#[cfg(not(target_arch = "wasm32"))]
mod host;
#[cfg(not(target_arch = "wasm32"))]
pub(crate) use host::bindings;
#[cfg(not(target_arch = "wasm32"))]
pub use host::*;

#[cfg(target_arch = "wasm32")]
mod guest;
#[cfg(target_arch = "wasm32")]
pub use guest::*;
#[cfg(target_arch = "wasm32")]
pub(crate) use guest::{dispatcher, platform, text_system, window, wit};

pub use schema::{
    ArgumentSchema, Describe, EventSchema, MethodSchema, Schema, TypeDefinition, TypeSchema,
};
pub use surface::{SurfaceApi, SurfaceApiCaller, ViewApi, ViewApiCaller};

use gpui::AppContext as _;
use serde::{Serialize, de::DeserializeOwned};
use std::cell::RefCell;
use std::marker::PhantomData;
use std::rc::Rc;

#[doc(hidden)]
pub use anyhow;
pub use embedded_gpui_macros::{data, interface, shared};
pub use gpui;
#[doc(hidden)]
pub use log;
pub use serde;

/// Identifies an object interface. Generated by [`interface`] as a struct with the
/// same name as the interface, so a handle to a shared counter reads
/// `Remote<CounterApi>`.
pub trait Interface: 'static {
    /// The interface as a runtime value: the same schema the macros compile against,
    /// for reflection (dynamic-language guests, inspectors, generated bindings).
    fn schema() -> Schema;
}

/// The interface's name for diagnostics and the (future) object-graph inspector:
/// `std::any::type_name`, so it costs no codegen and nothing on the wire checks it.
pub(crate) fn interface_name<S: Interface>() -> &'static str {
    std::any::type_name::<S>()
}

/// An interface this code knows nothing about: the type a forwarder uses for refs it
/// merely passes along. Any object can be connected as `Remote<Opaque>` and driven with
/// [`Remote::call_raw`].
pub struct Opaque;

impl Interface for Opaque {
    fn schema() -> Schema {
        Schema {
            name: "Opaque",
            methods: Vec::new(),
            events: Vec::new(),
            types: Vec::new(),
        }
    }
}

/// A message that can be sent to a shared object's home end.
pub trait Message: Serialize + DeserializeOwned + 'static {
    /// The entity kind this message addresses.
    type Spec: Interface;

    /// The value the home's handler returns. `()` for fire-and-forget casts.
    type Response: Serialize + DeserializeOwned + 'static;

    /// Stable method name used for dynamic dispatch on the home side.
    const METHOD: &'static str;
}

/// An event flowing from a shared object's home to every remote on the other end: the
/// boundary-crossing form of GPUI's `cx.emit`. Declared in a schema via the `events`
/// list of [`interface`]; received with [`Remote::subscribe`].
pub trait Event: Serialize + DeserializeOwned + 'static {
    /// The entity kind this event belongs to.
    type Spec: Interface;

    /// Stable event name used for dynamic dispatch on the remote side.
    const EVENT: &'static str;
}

/// Encoded message content: the serialized bytes plus the table of every [`Ref`] they
/// mention. Bytes name refs by index into `refs`, so a forwarder can rewrite which
/// objects a payload points at without parsing it, and the registry can account for
/// every capability in transit.
///
/// Payloads arriving from the other end are bound to the registry that delivered them
/// ([`Payload::registry`]), which is what lets a decoded `Ref` know where to connect.
#[derive(Clone, Default)]
pub struct Payload {
    pub bytes: Vec<u8>,
    pub refs: Vec<u64>,
    registry: Option<registry::WeakObjects>,
}

impl Payload {
    /// Wire content with no ref table (unit responses, control frames).
    pub fn empty() -> Self {
        Self::default()
    }

    /// Wire content with an explicit ref table, as a forwarder rebuilds it.
    pub fn from_parts(bytes: Vec<u8>, refs: Vec<u64>) -> Self {
        Self {
            bytes,
            refs,
            registry: None,
        }
    }

    /// The registry this payload arrived through, if it arrived at all.
    pub fn registry(&self) -> Option<Registry> {
        self.registry.clone().map(Registry)
    }

    pub(crate) fn bound(mut self, registry: registry::WeakObjects) -> Self {
        self.registry = Some(registry);
        self
    }
}

impl std::fmt::Debug for Payload {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("Payload")
            .field("bytes", &self.bytes.len())
            .field("refs", &self.refs)
            .finish()
    }
}

thread_local! {
    /// The ref table of the payload currently being encoded or decoded. Serde gives
    /// `Ref`'s (de)serializers no other channel to the enclosing payload.
    static REF_TABLE: RefCell<Option<RefTable>> = const { RefCell::new(None) };
}

struct RefTable {
    refs: Vec<u64>,
    registry: Option<registry::WeakObjects>,
}

fn with_ref_table<R>(table: RefTable, f: impl FnOnce() -> R) -> (R, RefTable) {
    let previous = REF_TABLE.with(|slot| slot.borrow_mut().replace(table));
    let result = f();
    let table = REF_TABLE.with(|slot| {
        let table = slot
            .borrow_mut()
            .take()
            .expect("ref table taken mid-encoding");
        *slot.borrow_mut() = previous;
        table
    });
    (result, table)
}

/// Serialize a value into a [`Payload`], collecting every [`Ref`] it mentions into the
/// ref table.
pub fn encode<T: Serialize>(value: &T) -> anyhow::Result<Payload> {
    let (bytes, table) = with_ref_table(
        RefTable {
            refs: Vec::new(),
            registry: None,
        },
        || serde_json::to_vec(value),
    );
    Ok(Payload {
        bytes: bytes?,
        refs: table.refs,
        registry: None,
    })
}

/// Deserialize a [`Payload`]; every [`Ref`] inside is bound to the registry the payload
/// arrived through, so it can be connected wherever it ends up.
pub fn decode<T: DeserializeOwned>(payload: &Payload) -> anyhow::Result<T> {
    let (value, _) = with_ref_table(
        RefTable {
            refs: payload.refs.clone(),
            registry: payload.registry.clone(),
        },
        || serde_json::from_slice(&payload.bytes),
    );
    Ok(value?)
}

/// What a method handler produced: an immediate response, or asynchronous work whose
/// result becomes the response when it resolves. Async handlers are what make caretakers
/// possible: a handler can await calls on other refs and pipe their responses through.
pub enum HandlerResponse {
    Ready(anyhow::Result<Payload>),
    Pending(gpui::Task<anyhow::Result<Payload>>),
}

/// A type-erased method handler on an entity's home side: decode, dispatch, encode the
/// response. Receives the method name so wildcard handlers can interpret it. Used
/// identically by the native host and the wasm guest.
pub type MethodHandler = Rc<dyn Fn(&str, &Payload, &mut gpui::App) -> HandlerResponse>;

/// Registering a handler under this name makes it the fallback for any method that has
/// no explicit entry: fully dynamic dispatch, decided by the entity at runtime. Purely a
/// [`Methods`] convention — the registry stores exactly one handler per object and never
/// interprets method names itself.
pub const WILDCARD_METHOD: &str = "*";

/// A dispatch table under construction: the dynamic escape hatch beneath the typed
/// [`Shared`] registration. Entities that interpret method names at runtime (or
/// wrappers that forward them wholesale via [`WILDCARD_METHOD`]) register here.
///
/// This is userspace: the table compiles down to the single dispatch closure the
/// registry actually stores, so name-keyed dispatch is one library convention among
/// possible ones, not a protocol feature.
pub struct Methods<S: Interface, T> {
    entity: gpui::WeakEntity<T>,
    map: std::collections::HashMap<String, MethodHandler>,
    _spec: PhantomData<S>,
}

impl<S: Interface, T: 'static> Methods<S, T> {
    #[doc(hidden)]
    pub fn new(entity: gpui::WeakEntity<T>) -> Self {
        Self {
            entity,
            map: std::collections::HashMap::new(),
            _spec: PhantomData,
        }
    }

    /// Register a handler for a method name, or for [`WILDCARD_METHOD`] to receive every
    /// method without an explicit entry.
    pub fn on(
        &mut self,
        method: impl Into<String>,
        handler: impl Fn(&gpui::Entity<T>, &str, &Payload, &mut gpui::App) -> anyhow::Result<Payload>
        + 'static,
    ) -> &mut Self {
        let entity = self.entity.clone();
        self.map.insert(
            method.into(),
            Rc::new(move |method, payload, cx| {
                HandlerResponse::Ready((|| {
                    let entity = entity
                        .upgrade()
                        .ok_or_else(|| anyhow::anyhow!("entity dropped"))?;
                    handler(&entity, method, payload, cx)
                })())
            }),
        );
        self
    }

    /// Register an asynchronous handler: it returns a task whose value becomes the
    /// response when it resolves, so the entity can await calls on other refs in between
    /// (forwarding, aggregation, caretakers).
    pub fn on_async(
        &mut self,
        method: impl Into<String>,
        handler: impl Fn(
            &gpui::Entity<T>,
            &str,
            &Payload,
            &mut gpui::App,
        ) -> gpui::Task<anyhow::Result<Payload>>
        + 'static,
    ) -> &mut Self {
        let entity = self.entity.clone();
        self.map.insert(
            method.into(),
            Rc::new(move |method, payload, cx| match entity.upgrade() {
                Some(entity) => HandlerResponse::Pending(handler(&entity, method, payload, cx)),
                None => HandlerResponse::Ready(Err(anyhow::anyhow!("entity dropped"))),
            }),
        );
        self
    }

    #[doc(hidden)]
    /// Compile the table into the one handler the registry stores: look the method up
    /// by name, fall back to the wildcard entry, or fail with a "no method" error.
    pub fn into_handler(self) -> MethodHandler {
        let map = self.map;
        Rc::new(move |method, payload, cx| {
            let Some(handler) = map.get(method).or_else(|| map.get(WILDCARD_METHOD)) else {
                return HandlerResponse::Ready(Err(anyhow::anyhow!(
                    "{} has no method {method:?}",
                    interface_name::<S>()
                )));
            };
            handler(method, payload, cx)
        })
    }
}

/// Forwards a home entity's typed events onto the wire; handed to
/// [`Shared::events`] by the share machinery.
pub type EventSink = Rc<dyn Fn(&str, Payload, &mut gpui::App)>;

/// An entity type that can be shared as an `S`: it knows how to register its method
/// handlers and how to wire its GPUI events to the boundary. Implemented by putting
/// [`macro@shared`] on the interface `impl` block; manual implementations are the
/// escape hatch for fully dynamic entities and generic wrappers.
pub trait Shared<S: Interface>: 'static + Sized {
    /// Install this type's method handlers into the dispatch table.
    fn methods(methods: &mut Methods<S, Self>);

    /// Wire the home entity's typed events to the boundary: subscribe to each event the
    /// schema declares and pipe it through `sink`. `cx.notify` crosses automatically and
    /// is not wired here.
    #[allow(unused_variables)]
    fn events(
        entity: &gpui::Entity<Self>,
        sink: EventSink,
        cx: &mut gpui::App,
    ) -> Vec<gpui::Subscription> {
        Vec::new()
    }

    /// Whether sharing keeps the entity alive until the other end releases it (the
    /// default, like handing out an `Entity<T>`). Entities whose lifetime belongs to
    /// their owner — a [`Surface`](surface::SurfaceApi) lives exactly as long as the
    /// embedder keeps it in its UI — return `false`: remotes to them may dangle, and
    /// calls then fail with "entity dropped".
    fn keep_alive() -> bool {
        true
    }
}

/// The sending half backing a [`Receipt`]: the response payload or an error string.
pub type ResponseSender = futures::channel::oneshot::Sender<Result<Payload, String>>;

fn decode_response<R: DeserializeOwned>(payload: Payload) -> anyhow::Result<R> {
    decode(&payload)
}

fn discard_response(_payload: Payload) -> anyhow::Result<()> {
    Ok(())
}

fn raw_response(payload: Payload) -> anyhow::Result<Payload> {
    Ok(payload)
}

fn missing_response<R>(_payload: Payload) -> anyhow::Result<R> {
    Err(anyhow::anyhow!("object went away before responding"))
}

/// The future returned by every call on a [`Remote`].
///
/// - `Receipt<R>` is a call's response: it resolves with the home handler's return
///   value. Handler errors arrive as `Err`, crossing the boundary as strings. Dropping
///   a receipt is fire-and-forget; the message is unaffected.
/// - `Receipt<Payload>` from [`Remote::call_raw`] resolves with the raw response,
///   undecoded — the forwarding primitive a caretaker pipes straight through; chain
///   [`Receipt::decoded`] or [`Receipt::acknowledged`] to interpret it.
pub struct Receipt<R = ()> {
    receiver: futures::channel::oneshot::Receiver<Result<Payload, String>>,
    decode: Box<dyn Fn(Payload) -> anyhow::Result<R>>,
}

impl Receipt<Payload> {
    #[doc(hidden)]
    pub fn channel() -> (ResponseSender, Self) {
        let (sender, receiver) = futures::channel::oneshot::channel();
        (
            sender,
            Self {
                receiver,
                decode: Box::new(raw_response),
            },
        )
    }

    /// Decode the raw response as `R` when it arrives.
    pub fn decoded<R: DeserializeOwned + 'static>(self) -> Receipt<R> {
        Receipt {
            receiver: self.receiver,
            decode: Box::new(decode_response::<R>),
        }
    }

    /// Keep only the acknowledgement: resolve with `()` once the home has responded.
    pub fn acknowledged(self) -> Receipt {
        Receipt {
            receiver: self.receiver,
            decode: Box::new(discard_response),
        }
    }

    /// Decode the response as a [`Ref`] and connect it, resolving with a live
    /// [`Remote`]: the receipt behind every ref-returning schema method.
    pub fn connected<S: Interface>(self) -> Receipt<Remote<S>> {
        Receipt {
            receiver: self.receiver,
            decode: Box::new(|payload| {
                let reference: Ref<S> = decode(&payload)?;
                Ok(reference.connect())
            }),
        }
    }
}

impl<R: 'static> Receipt<R> {
    /// A receipt that resolves with an error immediately; used when a message could not
    /// be encoded or dispatched at all.
    pub fn dropped() -> Self {
        let (_sender, receiver) = futures::channel::oneshot::channel();
        Self {
            receiver,
            decode: Box::new(missing_response::<R>),
        }
    }
}

impl<R> std::future::Future for Receipt<R> {
    type Output = anyhow::Result<R>;

    fn poll(
        self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Self::Output> {
        let this = self.get_mut();
        std::pin::Pin::new(&mut this.receiver)
            .poll(cx)
            .map(|result| {
                let outcome =
                    result.map_err(|_| anyhow::anyhow!("object went away before responding"))?;
                let payload = outcome.map_err(|error| anyhow::anyhow!("call failed: {error}"))?;
                (this.decode)(payload)
            })
    }
}

/// The one method-name convention between the two registries' own observer objects
/// (user objects never see it, and user schemas may use any method name whatsoever):
/// the home entity's `cx.notify`, sent as a plain call to each registered observer.
/// Subscribe and release are not names at all — they are structural wire frames.
pub(crate) const NOTIFY_EVENT: &str = "$notify";

/// The GPUI entity inside every [`Remote`] that incoming events land on; observe and
/// subscribe through [`Remote::observe`] / [`Remote::subscribe`] rather than directly.
pub struct RemoteSignal {
    _private: (),
}

impl RemoteSignal {
    pub(crate) fn new() -> Self {
        Self { _private: () }
    }
}

/// A shared object's event as it crosses the boundary, before typed decoding.
pub(crate) struct RawEvent {
    pub name: String,
    pub payload: Payload,
}

impl gpui::EventEmitter<RawEvent> for RemoteSignal {}

/// One end's object registry, as user code holds it: the operations that mint and
/// resolve capabilities, identical on both ends. Every [`Remote`], [`Ref`], and inbound
/// [`Payload`] knows the registry it belongs to ([`Remote::registry`],
/// [`Ref::registry`]), so anything that holds a capability can also share new objects
/// into the same connection — which is what lets a generic forwarder mint wrappers for
/// the refs passing through it.
///
/// The handle is weak: a registry outlived by its handles (the boundary was torn down)
/// makes sharing a no-op that returns refs nobody can reach.
#[derive(Clone)]
pub struct Registry(registry::WeakObjects);

impl Registry {
    pub(crate) fn new(objects: registry::WeakObjects) -> Self {
        Self(objects)
    }

    /// Share a local entity, returning a capability reference to embed in message or
    /// event payloads. The registry holds the entity alive until the other end's last
    /// remote drops (unless the type opts out via [`Shared::keep_alive`]).
    pub fn share<S, T>(&self, entity: &gpui::Entity<T>, cx: &mut gpui::App) -> Ref<S>
    where
        S: Interface,
        T: Shared<S>,
    {
        match self.0.upgrade() {
            Some(objects) => objects.share(entity, cx),
            None => Ref::detached(),
        }
    }

    /// [`Registry::share`] with a closure-registered dispatch table instead of a schema
    /// interface: the dynamic escape hatch. `cx.notify` still crosses; typed events are
    /// not wired (implement [`Shared`] manually if you need both).
    pub fn share_with<S, T>(
        &self,
        entity: &gpui::Entity<T>,
        register: impl FnOnce(&mut Methods<S, T>),
        cx: &mut gpui::App,
    ) -> Ref<S>
    where
        S: Interface,
        T: 'static,
    {
        match self.0.upgrade() {
            Some(objects) => objects.share_with(entity, register, cx),
            None => Ref::detached(),
        }
    }

    /// Attach to the other end's root object (the reserved address 0 means "your root"
    /// from either direction).
    pub fn root<S: Interface>(&self) -> Remote<S> {
        match self.0.upgrade() {
            Some(objects) => objects.root(),
            None => Remote::from_parts(self.0.clone(), 0, None),
        }
    }

    /// Resolve an object id in this registry. Prefer [`Ref::connect`]; this is for
    /// forwarders that hold ids out of a ref table rather than typed refs.
    pub fn connect<S: Interface>(&self, id: u64) -> Remote<S> {
        match self.0.upgrade() {
            Some(objects) => objects.connect_id(id),
            None => Remote::from_parts(self.0.clone(), id, None),
        }
    }

    /// Whether `id` is an object homed on this end.
    pub fn is_local(&self, id: u64) -> bool {
        self.0.upgrade().is_some_and(|objects| objects.is_local(id))
    }
}

/// A typed handle to an entity homed on the other side of the boundary. The nearest
/// thing to `Entity<T>` that can cross a sandbox wall:
///
/// - **call methods** — [`Remote::call`] / [`Remote::call_raw`], or the typed methods
///   a schema's generated `...Caller` trait adds (methods returning refs resolve
///   directly to connected `Remote`s); fire-and-forget is dropping the receipt;
/// - **react to it** — [`Remote::observe`] mirrors the home's `cx.notify`,
///   [`Remote::subscribe`] its typed `cx.emit` events;
/// - **refcounted** — clones share one guard; when the last clone of a ref-derived
///   remote drops, the home is told to let the entity go.
///
/// A remote is its registry handle plus an object id: it holds its registry weakly, so
/// it can outlive the boundary it came from (calls then resolve their receipts with
/// errors).
///
/// Reads are calls: state lives at the home, and anything you want to look at is a
/// method returning it (cache it locally with `embedded_gpui_util::Mirror` if you need
/// synchronous reads for rendering).
pub struct Remote<S: Interface> {
    objects: registry::WeakObjects,
    entity_id: u64,
    _guard: Option<Rc<dyn std::any::Any>>,
    _spec: PhantomData<fn() -> S>,
}

impl<S: Interface> Clone for Remote<S> {
    fn clone(&self) -> Self {
        Self {
            objects: self.objects.clone(),
            entity_id: self.entity_id,
            _guard: self._guard.clone(),
            _spec: PhantomData,
        }
    }
}

impl<S: Interface> std::fmt::Debug for Remote<S> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            formatter,
            "Remote<{}>({})",
            interface_name::<S>(),
            self.entity_id
        )
    }
}

impl<S: Interface> Remote<S> {
    pub(crate) fn from_parts(
        objects: registry::WeakObjects,
        entity_id: u64,
        guard: Option<Rc<dyn std::any::Any>>,
    ) -> Self {
        Self {
            objects,
            entity_id,
            _guard: guard,
            _spec: PhantomData,
        }
    }

    /// The registry this remote belongs to.
    pub fn registry(&self) -> Registry {
        Registry(self.objects.clone())
    }

    /// Mint the serializable capability reference for this entity, for embedding in
    /// message or event payloads.
    pub fn reference(&self) -> Ref<S> {
        Ref::new(self.entity_id, self.objects.clone())
    }

    fn request(&self, method: &str, payload: Payload) -> Receipt<Payload> {
        let (sender, receipt) = Receipt::channel();
        match self.objects.upgrade() {
            // Dropping `sender` resolves the receipt with an error.
            None => log::warn!("embedded_gpui: call after the boundary was torn down"),
            Some(objects) => objects.send(self.entity_id, method, payload, Some(sender)),
        }
        receipt
    }

    /// The signal this remote's events land on, created on first use; a detached,
    /// never-firing stand-in if the boundary or projection is gone.
    fn signal(&self, cx: &mut gpui::App) -> gpui::Entity<RemoteSignal> {
        self.objects
            .upgrade()
            .and_then(|objects| objects.signal_for(self.entity_id, cx))
            .unwrap_or_else(|| cx.new(|_| RemoteSignal::new()))
    }

    /// Call a typed method on the entity's home, resolving with its return value.
    /// Await the receipt for the value (or the error), or drop it for fire-and-forget;
    /// the message is applied either way.
    pub fn call<M: Message<Spec = S>>(
        &self,
        message: M,
        _cx: &mut gpui::App,
    ) -> Receipt<M::Response> {
        match encode(&message) {
            Ok(payload) => self.request(M::METHOD, payload).decoded(),
            Err(error) => {
                log::error!(
                    "embedded_gpui: failed to encode {}::{}: {error:#}",
                    interface_name::<S>(),
                    M::METHOD
                );
                Receipt::dropped()
            }
        }
    }

    /// Call a typed method whose return value is a capability reference, resolving
    /// with a live [`Remote`] already connected to it: object allocation across the
    /// boundary, one call from handle to handle. The schema's generated caller uses
    /// this for every `Ref`-returning method.
    pub fn call_connecting<M, S2>(&self, message: M, _cx: &mut gpui::App) -> Receipt<Remote<S2>>
    where
        M: Message<Spec = S, Response = Ref<S2>>,
        S2: Interface,
    {
        match encode(&message) {
            Ok(payload) => self.request(M::METHOD, payload).connected(),
            Err(error) => {
                log::error!(
                    "embedded_gpui: failed to encode {}::{}: {error:#}",
                    interface_name::<S>(),
                    M::METHOD
                );
                Receipt::dropped()
            }
        }
    }

    /// The dynamic escape hatch: call a method by name with a pre-encoded payload,
    /// resolving with the raw response. This is the forwarding primitive — a caretaker
    /// pipes these straight through — and the base of the typed verbs: chain
    /// [`Receipt::decoded`] for a typed value or [`Receipt::acknowledged`] for a bare
    /// ack.
    pub fn call_raw(
        &self,
        method: &str,
        payload: Payload,
        _cx: &mut gpui::App,
    ) -> Receipt<Payload> {
        self.request(method, payload)
    }

    /// React to the home entity's `cx.notify`, exactly like `cx.observe` on a local
    /// entity. The home notifies once on subscription, so observers always fire at least
    /// once after attaching.
    pub fn observe(
        &self,
        cx: &mut gpui::App,
        mut callback: impl FnMut(&mut gpui::App) + 'static,
    ) -> gpui::Subscription {
        let signal = self.signal(cx);
        cx.observe(&signal, move |_, cx| callback(cx))
    }

    /// React to a typed event the home emitted with `cx.emit`, exactly like
    /// `cx.subscribe` on a local entity.
    pub fn subscribe<E: Event<Spec = S>>(
        &self,
        cx: &mut gpui::App,
        mut callback: impl FnMut(&E, &mut gpui::App) + 'static,
    ) -> gpui::Subscription {
        let signal = self.signal(cx);
        cx.subscribe(&signal, move |_, event: &RawEvent, cx| {
            if event.name == E::EVENT {
                match decode::<E>(&event.payload) {
                    Ok(event) => callback(&event, cx),
                    Err(error) => log::error!(
                        "embedded_gpui: failed to decode {} event {:?}: {error:#}",
                        interface_name::<S>(),
                        E::EVENT
                    ),
                }
            }
        })
    }

    /// React to every event from the home, undecoded: the forwarding primitive for
    /// events, mirroring [`Remote::call_raw`] for calls.
    pub fn subscribe_raw(
        &self,
        cx: &mut gpui::App,
        mut callback: impl FnMut(&str, &Payload, &mut gpui::App) + 'static,
    ) -> gpui::Subscription {
        let signal = self.signal(cx);
        cx.subscribe(&signal, move |_, event: &RawEvent, cx| {
            callback(&event.name, &event.payload, cx)
        })
    }
}

/// A serializable capability reference to a shared entity of kind `S`: how objects
/// travel. An entity lives on one end; a [`Remote`] is how the other end holds it; a
/// `Ref` is how it moves through payloads (including call responses and events).
///
/// On the wire this is `{"$ref": index}` into the payload's ref table, which holds the
/// entity id — random, so possession is the authority: a ref can be known but never
/// guessed. The `$ref` shape makes refs findable in a payload without its schema, which
/// is what a dynamic-language guest needs. A ref also remembers the registry it was
/// minted by or arrived through, so [`Ref::connect`] turns it back into a live handle
/// from anywhere (schema methods declared to return a `Ref` do this on arrival,
/// resolving with a connected `Remote`).
pub struct Ref<S: Interface> {
    entity_id: u64,
    objects: registry::WeakObjects,
    _spec: PhantomData<fn() -> S>,
}

impl<S: Interface> Ref<S> {
    pub(crate) fn new(entity_id: u64, objects: registry::WeakObjects) -> Self {
        Self {
            entity_id,
            objects,
            _spec: PhantomData,
        }
    }

    /// A ref bound to no registry: connecting it yields a remote whose calls all fail.
    fn detached() -> Self {
        Self::new(0, registry::WeakObjects::detached())
    }

    pub fn entity_id(&self) -> u64 {
        self.entity_id
    }

    /// The registry this ref belongs to.
    pub fn registry(&self) -> Registry {
        Registry(self.objects.clone())
    }

    /// Attach to the entity: the same projection for the same ref, refcounted across
    /// clones; when the last clone drops, the home end is told to release the entity.
    pub fn connect(&self) -> Remote<S> {
        Registry(self.objects.clone()).connect(self.entity_id)
    }
}

impl<S: Interface> Clone for Ref<S> {
    fn clone(&self) -> Self {
        Self::new(self.entity_id, self.objects.clone())
    }
}

impl<S: Interface> std::fmt::Debug for Ref<S> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            formatter,
            "Ref<{}>({})",
            interface_name::<S>(),
            self.entity_id
        )
    }
}

impl<S: Interface> PartialEq for Ref<S> {
    fn eq(&self, other: &Self) -> bool {
        self.entity_id == other.entity_id
    }
}

impl<S: Interface> Eq for Ref<S> {}

impl<S: Interface> Serialize for Ref<S> {
    fn serialize<Ser: serde::Serializer>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error> {
        let index = REF_TABLE.with(|slot| {
            let mut slot = slot.borrow_mut();
            let table = slot.as_mut()?;
            let index = table.refs.len();
            table.refs.push(self.entity_id);
            Some(index as u64)
        });
        match index {
            Some(index) => RefWire { index }.serialize(serializer),
            None => Err(serde::ser::Error::custom(
                "a Ref can only be serialized inside embedded_gpui::encode",
            )),
        }
    }
}

/// The JSON shape of a ref: `{"$ref": index}`.
#[derive(Serialize, serde::Deserialize)]
struct RefWire {
    #[serde(rename = "$ref")]
    index: u64,
}

impl<'de, S: Interface> serde::Deserialize<'de> for Ref<S> {
    fn deserialize<De: serde::Deserializer<'de>>(deserializer: De) -> Result<Self, De::Error> {
        let index = RefWire::deserialize(deserializer)?.index as usize;
        let resolved = REF_TABLE.with(|slot| {
            let slot = slot.borrow();
            let table = slot.as_ref()?;
            let entity_id = *table.refs.get(index)?;
            Some((entity_id, table.registry.clone()))
        });
        match resolved {
            Some((entity_id, Some(registry))) => Ok(Self::new(entity_id, registry)),
            Some((_, None)) => Err(serde::de::Error::custom(
                "a Ref can only be decoded from a payload that arrived through a registry",
            )),
            None => Err(serde::de::Error::custom(format!(
                "ref index {index} is not in the payload's ref table"
            ))),
        }
    }
}
