//! GPUI running inside a Wasm component, embedded back into a native GPUI application.
//!
//! One crate serves both sides of the boundary:
//!
//! - the **object layer** (this file, always compiled): [`Remote`], [`Receipt`],
//!   [`Ref`], specs/messages/events, and the [`Shared`] home trait — the typed
//!   veneer over the dynamic wire, where everything is
//!   `(entity_id, method: string, payload: bytes)`;
//! - the **object registry** (`registry`, always compiled): one side-blind
//!   implementation of homes and projections that both ends run identically, configured
//!   only with a transport and an id namespace;
//! - the **host runtime** ([`PluginHost`] and friends; native targets only): wasmtime
//!   glue, display-list replay, and the byte transport for the registry;
//! - the **guest platform** (wasm32 targets only): a GPUI `Platform` implementation over
//!   the WIT protocol, plus [`Plugin`], [`register_plugin!`], and the guest-side
//!   transport (`share`, `share_root`, `root`, `connect`, and friends).
//!
//! See `DESIGN.md` at the repository root for the architecture.

// Lets macro-generated `#[serde(crate = "embedded_gpui::serde")]` attributes resolve
// even when the macro expands inside this crate itself.
extern crate self as embedded_gpui;

pub(crate) mod registry;

#[cfg(not(target_arch = "wasm32"))]
mod host;
#[cfg(not(target_arch = "wasm32"))]
pub(crate) use host::bindings;
#[cfg(not(target_arch = "wasm32"))]
pub use host::*;

#[cfg(target_arch = "wasm32")]
mod guest;
#[cfg(target_arch = "wasm32")]
pub use guest::*;
#[cfg(target_arch = "wasm32")]
pub(crate) use guest::{dispatcher, platform, text_system, window, wit};

use gpui::AppContext as _;
use serde::{Serialize, de::DeserializeOwned};
use std::marker::PhantomData;
use std::rc::Rc;

#[doc(hidden)]
pub use anyhow;
pub use embedded_gpui_macros::{data, interface, shared};
pub use gpui;
#[doc(hidden)]
pub use log;
pub use serde;

/// Identifies an object interface. Generated by [`interface`] as a struct with the
/// same name as the interface, so a handle to a shared counter reads
/// `Remote<CounterApi>`.
pub trait Interface: 'static {
    /// The interface's name, kept purely as diagnostic metadata for error messages;
    /// nothing on the wire checks it.
    const TYPE_NAME: &'static str;
}

/// A message that can be sent to a shared object's home end.
pub trait Message: Serialize + DeserializeOwned + 'static {
    /// The entity kind this message addresses.
    type Spec: Interface;

    /// The value the home's handler returns. `()` for fire-and-forget casts.
    type Response: Serialize + DeserializeOwned + 'static;

    /// Stable method name used for dynamic dispatch on the home side.
    const METHOD: &'static str;
}

/// An event flowing from a shared object's home to every remote on the other end: the
/// boundary-crossing form of GPUI's `cx.emit`. Declared in a schema via the `events`
/// list of [`interface`]; received with [`Remote::subscribe`].
pub trait Event: Serialize + DeserializeOwned + 'static {
    /// The entity kind this event belongs to.
    type Spec: Interface;

    /// Stable event name used for dynamic dispatch on the remote side.
    const EVENT: &'static str;
}

/// What a method handler produced: an immediate response, or asynchronous work whose
/// result becomes the response when it resolves. Async handlers are what make caretakers
/// possible: a handler can await calls on other refs and pipe their responses through.
pub enum HandlerResponse {
    Ready(anyhow::Result<Vec<u8>>),
    Pending(gpui::Task<anyhow::Result<Vec<u8>>>),
}

/// A type-erased method handler on an entity's home side: decode, dispatch, encode the
/// response. Receives the method name so wildcard handlers can interpret it. Used
/// identically by the native host and the wasm guest.
pub type MethodHandler = Rc<dyn Fn(&str, &[u8], &mut gpui::App) -> HandlerResponse>;

/// Registering a handler under this name makes it the fallback for any method that has no
/// explicit entry: fully dynamic dispatch, decided by the entity at runtime.
pub const WILDCARD_METHOD: &str = "*";

/// A dispatch table under construction: the dynamic escape hatch beneath the typed
/// [`Shared`] registration. Entities that interpret method names at runtime (or
/// wrappers that forward them wholesale via [`WILDCARD_METHOD`]) register here.
pub struct Methods<S: Interface, T> {
    entity: gpui::WeakEntity<T>,
    map: std::collections::HashMap<String, MethodHandler>,
    _spec: PhantomData<S>,
}

impl<S: Interface, T: 'static> Methods<S, T> {
    #[doc(hidden)]
    pub fn new(entity: gpui::WeakEntity<T>) -> Self {
        Self {
            entity,
            map: std::collections::HashMap::new(),
            _spec: PhantomData,
        }
    }

    /// Register a handler for a method name, or for [`WILDCARD_METHOD`] to receive every
    /// method without an explicit entry.
    pub fn on(
        &mut self,
        method: impl Into<String>,
        handler: impl Fn(&gpui::Entity<T>, &str, &[u8], &mut gpui::App) -> anyhow::Result<Vec<u8>>
        + 'static,
    ) -> &mut Self {
        let entity = self.entity.clone();
        self.map.insert(
            method.into(),
            Rc::new(move |method, payload, cx| {
                HandlerResponse::Ready((|| {
                    let entity = entity
                        .upgrade()
                        .ok_or_else(|| anyhow::anyhow!("entity dropped"))?;
                    handler(&entity, method, payload, cx)
                })())
            }),
        );
        self
    }

    /// Register an asynchronous handler: it returns a task whose value becomes the
    /// response when it resolves, so the entity can await calls on other refs in between
    /// (forwarding, aggregation, caretakers).
    pub fn on_async(
        &mut self,
        method: impl Into<String>,
        handler: impl Fn(
            &gpui::Entity<T>,
            &str,
            &[u8],
            &mut gpui::App,
        ) -> gpui::Task<anyhow::Result<Vec<u8>>>
        + 'static,
    ) -> &mut Self {
        let entity = self.entity.clone();
        self.map.insert(
            method.into(),
            Rc::new(move |method, payload, cx| match entity.upgrade() {
                Some(entity) => HandlerResponse::Pending(handler(&entity, method, payload, cx)),
                None => HandlerResponse::Ready(Err(anyhow::anyhow!("entity dropped"))),
            }),
        );
        self
    }

    #[doc(hidden)]
    pub fn into_map(self) -> std::collections::HashMap<String, MethodHandler> {
        self.map
    }
}

/// Forwards a home entity's typed events onto the wire; handed to
/// [`Shared::events`] by the share machinery.
pub type EventSink = Rc<dyn Fn(&str, Vec<u8>, &mut gpui::App)>;

/// An entity type that can be shared as an `S`: it knows how
/// to register its method handlers and how to wire its GPUI events to the boundary.
/// Implemented by putting [`macro@shared`] on the interface `impl` block; manual
/// implementations are the escape hatch for fully dynamic entities and generic wrappers.
pub trait Shared<S: Interface>: 'static + Sized {
    /// Install this type's method handlers into the dispatch table.
    fn methods(methods: &mut Methods<S, Self>);

    /// Wire the home entity's typed events to the boundary: subscribe to each event the
    /// schema declares and pipe it through `sink`. `cx.notify` crosses automatically and
    /// is not wired here.
    #[allow(unused_variables)]
    fn events(
        entity: &gpui::Entity<Self>,
        sink: EventSink,
        cx: &mut gpui::App,
    ) -> Vec<gpui::Subscription> {
        Vec::new()
    }
}

/// The sending half backing a [`Receipt`]: the serialized response or an error string.
pub type ResponseSender = futures::channel::oneshot::Sender<Result<Vec<u8>, String>>;

fn decode_response<R: DeserializeOwned>(bytes: Vec<u8>) -> anyhow::Result<R> {
    decode(&bytes)
}

fn discard_response(_bytes: Vec<u8>) -> anyhow::Result<()> {
    Ok(())
}

fn raw_response(bytes: Vec<u8>) -> anyhow::Result<Vec<u8>> {
    Ok(bytes)
}

fn missing_response<R>(_bytes: Vec<u8>) -> anyhow::Result<R> {
    Err(anyhow::anyhow!("object went away before responding"))
}

/// The future returned by every send and call on a [`Remote`].
///
/// - `Receipt` (of `()`) is a send's acknowledgement: it resolves once the home has
///   applied the message. Dropping it is fire-and-forget; the message is unaffected.
/// - `Receipt<R>` is a call's response: it resolves with the home handler's return
///   value. Handler errors arrive as `Err`, crossing the boundary as strings.
/// - `Receipt<Vec<u8>>` from [`Remote::forward`] resolves with the raw response bytes,
///   undecoded — the forwarding primitive a caretaker pipes straight through.
pub struct Receipt<R = ()> {
    receiver: futures::channel::oneshot::Receiver<Result<Vec<u8>, String>>,
    decode: Box<dyn Fn(Vec<u8>) -> anyhow::Result<R>>,
}

impl Receipt<Vec<u8>> {
    #[doc(hidden)]
    pub fn channel() -> (ResponseSender, Self) {
        let (sender, receiver) = futures::channel::oneshot::channel();
        (
            sender,
            Self {
                receiver,
                decode: Box::new(raw_response),
            },
        )
    }

    /// Decode the raw response as `R` when it arrives.
    pub fn decoded<R: DeserializeOwned + 'static>(self) -> Receipt<R> {
        Receipt {
            receiver: self.receiver,
            decode: Box::new(decode_response::<R>),
        }
    }

    /// Keep only the acknowledgement: resolve with `()` once the home has responded.
    pub fn acknowledged(self) -> Receipt {
        Receipt {
            receiver: self.receiver,
            decode: Box::new(discard_response),
        }
    }

    /// Decode the response as a [`Ref`] and connect it in `objects`, resolving
    /// with a live [`Remote`]: the receipt behind every ref-returning schema method.
    pub(crate) fn connected<S: Interface>(
        self,
        objects: registry::WeakObjects,
    ) -> Receipt<Remote<S>> {
        Receipt {
            receiver: self.receiver,
            decode: Box::new(move |bytes| {
                let reference: Ref<S> = decode(&bytes)?;
                let objects = objects
                    .upgrade()
                    .ok_or_else(|| anyhow::anyhow!("the boundary was torn down"))?;
                Ok(objects.connect(reference))
            }),
        }
    }
}

impl<R: 'static> Receipt<R> {
    /// A receipt that resolves with an error immediately; used when a message could not
    /// be encoded or dispatched at all.
    pub fn dropped() -> Self {
        let (_sender, receiver) = futures::channel::oneshot::channel();
        Self {
            receiver,
            decode: Box::new(missing_response::<R>),
        }
    }
}

impl<R> std::future::Future for Receipt<R> {
    type Output = anyhow::Result<R>;

    fn poll(
        self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Self::Output> {
        let this = self.get_mut();
        std::pin::Pin::new(&mut this.receiver)
            .poll(cx)
            .map(|result| {
                let outcome =
                    result.map_err(|_| anyhow::anyhow!("object went away before responding"))?;
                let bytes = outcome.map_err(|error| anyhow::anyhow!("call failed: {error}"))?;
                (this.decode)(bytes)
            })
    }
}

pub fn encode<T: Serialize>(value: &T) -> anyhow::Result<Vec<u8>> {
    Ok(serde_json::to_vec(value)?)
}

pub fn decode<T: DeserializeOwned>(bytes: &[u8]) -> anyhow::Result<T> {
    Ok(serde_json::from_slice(bytes)?)
}

/// Reserved event name (runtime plumbing): the home entity's `cx.notify`, crossing the
/// boundary so remotes' observers fire.
pub(crate) const NOTIFY_EVENT: &str = "$notify";

/// Reserved control method (runtime plumbing, never sent by user code): a remote
/// announcing interest in an entity. The home starts sending events to it (and answers
/// with an initial `$notify`).
pub(crate) const SUBSCRIBE_METHOD: &str = "$subscribe";

/// Reserved control method (runtime plumbing, never sent by user code): a remote
/// relinquishing an entity. Anonymous homes drop their strong handle, letting the entity
/// die when nothing else owns it.
pub(crate) const RELEASE_METHOD: &str = "$release";

/// The GPUI entity inside every [`Remote`] that incoming events land on; observe and
/// subscribe through [`Remote::observe`] / [`Remote::subscribe`] rather than directly.
pub struct RemoteSignal {
    _private: (),
}

impl RemoteSignal {
    pub(crate) fn new() -> Self {
        Self { _private: () }
    }
}

/// A shared object's event as it crosses the boundary, before typed decoding.
pub(crate) struct RawEvent {
    pub name: String,
    pub payload: Vec<u8>,
}

impl gpui::EventEmitter<RawEvent> for RemoteSignal {}

/// A typed handle to an entity homed on the other side of the boundary. The nearest
/// thing to `Entity<T>` that can cross a sandbox wall:
///
/// - **call methods** — [`Remote::send`] / [`Remote::call`], or the typed methods a
///   schema's generated `...Caller` trait adds (methods returning refs resolve
///   directly to connected `Remote`s);
/// - **react to it** — [`Remote::observe`] mirrors the home's `cx.notify`,
///   [`Remote::subscribe`] its typed `cx.emit` events;
/// - **refcounted** — clones share one guard; when the last clone of a ref-derived
///   remote drops, the home is told to let the entity go.
///
/// A remote is its registry handle plus an object id: it holds its registry weakly, so
/// it can outlive the boundary it came from (sends then resolve their receipts with
/// errors).
///
/// Reads are calls: state lives at the home, and anything you want to look at is a
/// method returning it (cache it locally with `embedded_gpui_util::Mirror` if you need
/// synchronous reads for rendering).
pub struct Remote<S: Interface> {
    objects: registry::WeakObjects,
    entity_id: u64,
    _guard: Option<Rc<dyn std::any::Any>>,
    _spec: PhantomData<fn() -> S>,
}

impl<S: Interface> Clone for Remote<S> {
    fn clone(&self) -> Self {
        Self {
            objects: self.objects.clone(),
            entity_id: self.entity_id,
            _guard: self._guard.clone(),
            _spec: PhantomData,
        }
    }
}

impl<S: Interface> Remote<S> {
    #[doc(hidden)]
    pub(crate) fn from_parts(
        objects: registry::WeakObjects,
        entity_id: u64,
        guard: Option<Rc<dyn std::any::Any>>,
    ) -> Self {
        Self {
            objects,
            entity_id,
            _guard: guard,
            _spec: PhantomData,
        }
    }

    /// Mint the serializable capability reference for this entity, for embedding in
    /// message or event payloads.
    pub fn reference(&self) -> Ref<S> {
        Ref::from_raw(self.entity_id)
    }

    fn request(&self, method: &str, payload: Vec<u8>, _cx: &mut gpui::App) -> Receipt<Vec<u8>> {
        let (sender, receipt) = Receipt::channel();
        match self.objects.upgrade() {
            // Dropping `sender` resolves the receipt with an error.
            None => log::warn!("embedded_gpui: send after the boundary was torn down"),
            Some(objects) => objects.send(self.entity_id, method, payload, Some(sender)),
        }
        receipt
    }

    /// The signal this remote's events land on, created on first use; a detached,
    /// never-firing stand-in if the boundary or projection is gone.
    fn signal(&self, cx: &mut gpui::App) -> gpui::Entity<RemoteSignal> {
        self.objects
            .upgrade()
            .and_then(|objects| objects.signal_for(self.entity_id, cx))
            .unwrap_or_else(|| cx.new(|_| RemoteSignal::new()))
    }

    /// Send a typed message to the entity's home. Await the receipt to know it was
    /// applied; drop it for fire-and-forget.
    pub fn send<M: Message<Spec = S>>(&self, message: M, cx: &mut gpui::App) -> Receipt {
        match encode(&message) {
            Ok(payload) => self.request(M::METHOD, payload, cx).acknowledged(),
            Err(error) => {
                log::error!(
                    "embedded_gpui: failed to encode {}::{}: {error:#}",
                    S::TYPE_NAME,
                    M::METHOD
                );
                Receipt::dropped()
            }
        }
    }

    /// Call a typed method on the entity's home, resolving with its return value.
    pub fn call<M: Message<Spec = S>>(
        &self,
        message: M,
        cx: &mut gpui::App,
    ) -> Receipt<M::Response> {
        match encode(&message) {
            Ok(payload) => self.request(M::METHOD, payload, cx).decoded(),
            Err(error) => {
                log::error!(
                    "embedded_gpui: failed to encode {}::{}: {error:#}",
                    S::TYPE_NAME,
                    M::METHOD
                );
                Receipt::dropped()
            }
        }
    }

    /// Call a typed method whose return value is a capability reference, resolving
    /// with a live [`Remote`] already connected to it: object allocation across the
    /// boundary, one call from handle to handle. The schema's generated caller uses
    /// this for every `Ref`-returning method.
    pub fn call_connecting<M, S2>(&self, message: M, cx: &mut gpui::App) -> Receipt<Remote<S2>>
    where
        M: Message<Spec = S, Response = Ref<S2>>,
        S2: Interface,
    {
        match encode(&message) {
            Ok(payload) => self
                .request(M::METHOD, payload, cx)
                .connected(self.objects.clone()),
            Err(error) => {
                log::error!(
                    "embedded_gpui: failed to encode {}::{}: {error:#}",
                    S::TYPE_NAME,
                    M::METHOD
                );
                Receipt::dropped()
            }
        }
    }

    /// The dynamic escape hatch: send an arbitrary method and payload.
    pub fn send_raw(&self, method: &str, payload: Vec<u8>, cx: &mut gpui::App) -> Receipt {
        self.request(method, payload, cx).acknowledged()
    }

    /// The dynamic call escape hatch: call an arbitrary method and decode the response.
    pub fn call_raw<R: DeserializeOwned + 'static>(
        &self,
        method: &str,
        payload: Vec<u8>,
        cx: &mut gpui::App,
    ) -> Receipt<R> {
        self.request(method, payload, cx).decoded()
    }

    /// Call a method by name with a pre-encoded payload, resolving with the raw response
    /// bytes. The forwarding primitive: a caretaker pipes these straight through.
    pub fn forward(&self, method: &str, payload: Vec<u8>, cx: &mut gpui::App) -> Receipt<Vec<u8>> {
        self.request(method, payload, cx)
    }

    /// React to the home entity's `cx.notify`, exactly like `cx.observe` on a local
    /// entity. The home notifies once on subscription, so observers always fire at least
    /// once after attaching.
    pub fn observe(
        &self,
        cx: &mut gpui::App,
        mut callback: impl FnMut(&mut gpui::App) + 'static,
    ) -> gpui::Subscription {
        let signal = self.signal(cx);
        cx.observe(&signal, move |_, cx| callback(cx))
    }

    /// React to a typed event the home emitted with `cx.emit`, exactly like
    /// `cx.subscribe` on a local entity.
    pub fn subscribe<E: Event<Spec = S>>(
        &self,
        cx: &mut gpui::App,
        mut callback: impl FnMut(&E, &mut gpui::App) + 'static,
    ) -> gpui::Subscription {
        let signal = self.signal(cx);
        cx.subscribe(&signal, move |_, event: &RawEvent, cx| {
            if event.name == E::EVENT {
                match decode::<E>(&event.payload) {
                    Ok(event) => callback(&event, cx),
                    Err(error) => log::error!(
                        "embedded_gpui: failed to decode {} event {:?}: {error:#}",
                        S::TYPE_NAME,
                        E::EVENT
                    ),
                }
            }
        })
    }

    /// React to every event from the home, undecoded: the forwarding primitive for
    /// events, mirroring [`Remote::forward`] for calls.
    pub fn subscribe_raw(
        &self,
        cx: &mut gpui::App,
        mut callback: impl FnMut(&str, &[u8], &mut gpui::App) + 'static,
    ) -> gpui::Subscription {
        let signal = self.signal(cx);
        cx.subscribe(&signal, move |_, event: &RawEvent, cx| {
            callback(&event.name, &event.payload, cx)
        })
    }
}

/// A serializable capability reference to a shared object of kind `S`: how objects
/// travel. An entity lives on one end; a [`Remote`] is how the other end holds it; a
/// `Ref` is how it moves through payloads (including call responses and events).
///
/// On the wire this is nothing but the entity id — random, so possession is the
/// authority: a ref can be known but never guessed. Sharing the same entity twice with
/// different method tables mints attenuated capabilities. Turn a ref back into a live
/// handle with `connect` (schema methods declared to return a `Ref` do this on arrival,
/// resolving with a connected `Remote`).
pub struct Ref<S: Interface> {
    entity_id: u64,
    _spec: PhantomData<fn() -> S>,
}

impl<S: Interface> Ref<S> {
    #[doc(hidden)]
    pub fn from_raw(entity_id: u64) -> Self {
        Self {
            entity_id,
            _spec: PhantomData,
        }
    }

    pub fn entity_id(&self) -> u64 {
        self.entity_id
    }
}

impl<S: Interface> Clone for Ref<S> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<S: Interface> Copy for Ref<S> {}

impl<S: Interface> std::fmt::Debug for Ref<S> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(formatter, "Ref<{}>({})", S::TYPE_NAME, self.entity_id)
    }
}

impl<S: Interface> PartialEq for Ref<S> {
    fn eq(&self, other: &Self) -> bool {
        self.entity_id == other.entity_id
    }
}

impl<S: Interface> Eq for Ref<S> {}

impl<S: Interface> Serialize for Ref<S> {
    fn serialize<Ser: serde::Serializer>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error> {
        serializer.serialize_u64(self.entity_id)
    }
}

impl<'de, S: Interface> serde::Deserialize<'de> for Ref<S> {
    fn deserialize<De: serde::Deserializer<'de>>(deserializer: De) -> Result<Self, De::Error> {
        Ok(Self::from_raw(u64::deserialize(deserializer)?))
    }
}
