//! TypeScript declarations generated from interface schemas: the typed face of a
//! dynamic-language guest. A JS plugin binds to remotes by method name at runtime; these
//! declarations give its author (or an agent writing it) type checking against the same
//! schema the Rust side compiled.
//!
//! The runtime shape assumed here is the one this crate's runtime provides: a
//! remote to an interface `Foo` is a `Remote<Foo>` whose methods return promises, with
//! `observe`/`subscribe` for the home's notifies and events, and refs in payloads
//! arriving as remotes.

use std::fmt::Write as _;

use embedded_gpui::schema::{Schema, TypeDefinition, TypeKind, TypeSchema, VariantFields};

/// Render `.d.ts` declarations for a set of interfaces: one `interface` per schema with
/// promise-returning methods, one type alias or interface per named payload type, and
/// the `Remote` helpers the runtime's globals are typed against.
pub fn declarations(schemas: &[Schema]) -> String {
    let mut out = String::new();
    out.push_str("// Generated by embedded_gpui from the Rust interface schemas. Do not edit.\n\n");
    out.push_str(PRELUDE);

    let mut types: Vec<&TypeDefinition> = Vec::new();
    for schema in schemas {
        for definition in &schema.types {
            if !types
                .iter()
                .any(|existing| existing.name == definition.name)
            {
                types.push(definition);
            }
        }
    }
    for definition in types {
        write_definition(&mut out, definition);
    }

    for schema in schemas {
        let _ = writeln!(out, "export interface {} {{", schema.name);
        for method in &schema.methods {
            let arguments: Vec<String> = method
                .arguments
                .iter()
                .map(|argument| format!("{}: {}", argument.name, ts_type(&argument.ty)))
                .collect();
            let _ = writeln!(
                out,
                "  {}({}): Promise<{}>;",
                method.name,
                arguments.join(", "),
                ts_type(&method.response)
            );
        }
        if !schema.events.is_empty() {
            let _ = writeln!(out, "  subscribe<E extends keyof {}Events>(", schema.name);
            let _ = writeln!(
                out,
                "    event: E,\n    callback: (event: {}Events[E]) => void,\n  ): Subscription;",
                schema.name
            );
        }
        out.push_str("}\n\n");
        if !schema.events.is_empty() {
            let _ = writeln!(out, "export interface {}Events {{", schema.name);
            for event in &schema.events {
                let _ = writeln!(out, "  {}: {};", event.name, ts_type(&event.ty));
            }
            out.push_str("}\n\n");
        }
    }
    out
}

const PRELUDE: &str = "\
/** A handle to an object homed on the other end of the boundary. */
export interface Remote {
  /** React to the home's `cx.notify`. Fires once on subscription. */
  observe(callback: () => void): Subscription;
  /** Call a method by name; the dynamic escape hatch under the typed methods. */
  call(method: string, args?: object): Promise<unknown>;
}

export interface Subscription {
  cancel(): void;
}

";

fn write_definition(out: &mut String, definition: &TypeDefinition) {
    match &definition.kind {
        TypeKind::Struct(fields) => {
            let _ = writeln!(out, "export interface {} {{", definition.name);
            for field in fields {
                let _ = writeln!(out, "  {}: {};", field.name, ts_type(&field.ty));
            }
            out.push_str("}\n\n");
        }
        TypeKind::Enum(variants) => {
            let _ = writeln!(out, "export type {} =", definition.name);
            for variant in variants {
                let rendered = match &variant.fields {
                    VariantFields::Unit => format!("\"{}\"", variant.name),
                    VariantFields::Named(fields) => {
                        let fields: Vec<String> = fields
                            .iter()
                            .map(|field| format!("{}: {}", field.name, ts_type(&field.ty)))
                            .collect();
                        format!("{{ {}: {{ {} }} }}", variant.name, fields.join("; "))
                    }
                    VariantFields::Unnamed(types) => match types.as_slice() {
                        [single] => format!("{{ {}: {} }}", variant.name, ts_type(single)),
                        many => {
                            let types: Vec<String> = many.iter().map(ts_type).collect();
                            format!("{{ {}: [{}] }}", variant.name, types.join(", "))
                        }
                    },
                };
                let _ = writeln!(out, "  | {rendered}");
            }
            out.push_str(";\n\n");
        }
    }
}

fn ts_type(ty: &TypeSchema) -> String {
    match ty {
        TypeSchema::Unit => "void".into(),
        TypeSchema::Bool => "boolean".into(),
        TypeSchema::Integer | TypeSchema::Float => "number".into(),
        TypeSchema::String => "string".into(),
        TypeSchema::Option(inner) => format!("{} | null", ts_type(inner)),
        TypeSchema::List(inner) => format!("{}[]", wrap(inner)),
        TypeSchema::Map(inner) => format!("Record<string, {}>", ts_type(inner)),
        TypeSchema::Tuple(items) => {
            let items: Vec<String> = items.iter().map(ts_type).collect();
            format!("[{}]", items.join(", "))
        }
        TypeSchema::Ref(interface) => format!("{interface} & Remote"),
        TypeSchema::Named(name) => (*name).into(),
    }
}

/// Parenthesize union and intersection types before a `[]` suffix.
fn wrap(ty: &TypeSchema) -> String {
    match ty {
        TypeSchema::Option(_) | TypeSchema::Ref(_) => format!("({})", ts_type(ty)),
        _ => ts_type(ty),
    }
}
