//! Proc macros for `embedded_gpui`. See [`macro@interface`].

use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::parse::{Parse, ParseStream};
use syn::spanned::Spanned as _;
use syn::{FnArg, Ident, ItemImpl, ItemTrait, Token, TraitItem, Type, bracketed};

/// Turns a trait declaration into a complete object interface.
///
/// ```ignore
/// #[interface(events = [Milestone])]
/// pub trait CounterApi {
///     fn increment(&mut self, by: u32, cx: &mut gpui::Context<Self>) -> u32;
///     fn count(&mut self, cx: &mut gpui::Context<Self>) -> u32;
/// }
/// ```
///
/// One name is the whole interface. The trait syntax is consumed and replaced by:
///
/// - `pub struct CounterApi` implementing `Interface` — so handles read
///   `Remote<CounterApi>`, refs read `Ref<CounterApi>`, and homes are declared
///   `#[shared] impl CounterApi for MyEntity { ... }`;
/// - one message struct per method (`Increment { ... }`), named by PascalCasing the
///   method, with `Message` wired to the method's return type;
/// - a `Event` impl for each type in `events`, so the home's ordinary
///   `cx.emit(Milestone { .. })` crosses the boundary to `Remote::subscribe`
///   (each event type must be an `EventEmitter` event of the home entity, as usual);
/// - `pub trait CounterApiCaller`, implemented for `Remote<CounterApi>`: one typed
///   method per interface method, so remotes get `.increment(by, cx) -> Receipt<u32>`;
/// - hidden `CounterApi::register_increment(...)` functions taking a checked function
///   pointer per method, which is how `#[shared]` type-checks a home
///   implementation against this schema.
///
/// Method shape: `&mut self`, any number of serde-serializable arguments, and a final
/// `cx: &mut Context<Self>` parameter.
///
/// Methods may be declared `async fn name(...) -> R`. The home implements them as
/// ordinary methods returning `gpui::Task<anyhow::Result<R>>` (which is what `cx.spawn`
/// produces); the response is sent when the task resolves, so the handler can await
/// calls on other capabilities in between. Callers see the same `Receipt<R>` either way.
#[proc_macro_attribute]
pub fn interface(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args = syn::parse_macro_input!(attr as InterfaceArgs);
    let item_trait = syn::parse_macro_input!(item as ItemTrait);
    match expand_interface(args, item_trait) {
        Ok(tokens) => tokens.into(),
        Err(error) => error.to_compile_error().into(),
    }
}

/// Declares an entity type as an implementation of an interface:
///
/// ```ignore
/// #[shared]
/// impl CounterApi for Counter {
///     fn increment(&mut self, by: u32, cx: &mut gpui::Context<Self>) -> u32 { ... }
///     fn count(&mut self, cx: &mut gpui::Context<Self>) -> u32 { ... }
/// }
/// ```
///
/// `CounterApi` names the interface (the spec struct generated by
/// [`macro@interface`]); the block's methods become ordinary methods of the
/// entity, and the attribute implements `Shared<CounterApi>` by registering each
/// one through the schema's checked registration functions — a signature mismatch is a
/// compile error. If the interface declares events, the home entity must also be a gpui
/// `EventEmitter` for each event type.
///
/// A method the block omits stays callable-but-unhandled: callers get a "no method"
/// error at runtime, not a compile error, so keep the block complete.
#[proc_macro_attribute]
pub fn shared(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let item_impl = syn::parse_macro_input!(item as ItemImpl);
    match expand_home(item_impl) {
        Ok(tokens) => tokens.into(),
        Err(error) => error.to_compile_error().into(),
    }
}

/// Derives everything a struct or enum needs to travel in object payloads
/// (message arguments, return values, event fields): `Clone`, `Debug`, and serde
/// `Serialize`/`Deserialize` through `embedded_gpui`'s re-exported serde, so schema
/// crates need no serde dependency of their own.
#[proc_macro_attribute]
pub fn data(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let item = proc_macro2::TokenStream::from(item);
    quote! {
        #[derive(
            Clone,
            Debug,
            embedded_gpui::serde::Serialize,
            embedded_gpui::serde::Deserialize,
        )]
        #[serde(crate = "embedded_gpui::serde")]
        #item
    }
    .into()
}

struct InterfaceArgs {
    events: Vec<syn::Path>,
}

impl Parse for InterfaceArgs {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let mut events = Vec::new();
        let mut first = true;
        while !input.is_empty() {
            if !first {
                input.parse::<Token![,]>()?;
                if input.is_empty() {
                    break;
                }
            }
            first = false;
            let key: Ident = input.parse()?;
            if key == "events" {
                input.parse::<Token![=]>()?;
                let content;
                bracketed!(content in input);
                events = content
                    .parse_terminated(syn::Path::parse, Token![,])?
                    .into_iter()
                    .collect();
            } else {
                return Err(syn::Error::new(
                    key.span(),
                    "expected `events = [Type, ...]`",
                ));
            }
        }
        Ok(Self { events })
    }
}

struct Method {
    ident: Ident,
    message_ident: Ident,
    method_name: String,
    field_names: Vec<Ident>,
    field_types: Vec<Type>,
    response: proc_macro2::TokenStream,
    /// `Some(T)` when the response type is syntactically `Ref<T>`: the caller
    /// then resolves with a connected `Remote<T>` instead of the bare ref.
    ref_response: Option<Type>,
    is_async: bool,
}

/// Matches a response type of the shape `Ref<T>` (by any path), yielding `T`.
fn ref_inner(ty: &syn::Type) -> Option<Type> {
    let syn::Type::Path(path) = ty else {
        return None;
    };
    let segment = path.path.segments.last()?;
    if segment.ident != "Ref" {
        return None;
    }
    let syn::PathArguments::AngleBracketed(arguments) = &segment.arguments else {
        return None;
    };
    if arguments.args.len() != 1 {
        return None;
    }
    match arguments.args.first()? {
        syn::GenericArgument::Type(inner) => Some(inner.clone()),
        _ => None,
    }
}

fn expand_interface(
    args: InterfaceArgs,
    mut item_trait: ItemTrait,
) -> syn::Result<proc_macro2::TokenStream> {
    let InterfaceArgs { events } = args;

    let vis = item_trait.vis.clone();
    let spec_ident = item_trait.ident.clone();
    // The interface's own name doubles as the diagnostic type name; nothing on the
    // wire checks it.
    let type_name = spec_ident.to_string();
    let doc_attrs: Vec<_> = item_trait
        .attrs
        .iter()
        .filter(|attr| attr.path().is_ident("doc"))
        .cloned()
        .collect();

    let mut methods = Vec::new();
    for item in &mut item_trait.items {
        let TraitItem::Fn(function) = item else {
            continue;
        };
        let sig = &mut function.sig;
        let is_async = sig.asyncness.take().is_some();
        let mut inputs = sig.inputs.iter();
        match inputs.next() {
            Some(FnArg::Receiver(receiver)) if receiver.mutability.is_some() => {}
            other => {
                return Err(syn::Error::new(
                    other.span(),
                    "interface methods take `&mut self`",
                ));
            }
        }
        let mut typed: Vec<_> = inputs.collect();
        // The final parameter is the context; everything between self and it becomes
        // message fields.
        if typed.pop().is_none() {
            return Err(syn::Error::new(
                sig.span(),
                "interface methods end with `cx: &mut Context<Self>`",
            ));
        }
        let mut field_names = Vec::new();
        let mut field_types = Vec::new();
        for arg in typed {
            let FnArg::Typed(arg) = arg else {
                return Err(syn::Error::new(arg.span(), "unexpected receiver"));
            };
            let syn::Pat::Ident(pat) = &*arg.pat else {
                return Err(syn::Error::new(
                    arg.pat.span(),
                    "message parameters must be plain identifiers",
                ));
            };
            field_names.push(pat.ident.clone());
            field_types.push((*arg.ty).clone());
        }
        let (response, ref_response) = match &sig.output {
            syn::ReturnType::Default => (quote!(()), None),
            syn::ReturnType::Type(_, ty) => (quote!(#ty), ref_inner(ty)),
        };
        let method_name = sig.ident.to_string();
        methods.push(Method {
            ident: sig.ident.clone(),
            message_ident: format_ident!("{}", pascal_case(&method_name), span = sig.ident.span()),
            method_name,
            field_names,
            field_types,
            response,
            ref_response,
            is_async,
        });
    }

    let message_items = methods.iter().map(|method| {
        let Method {
            message_ident,
            method_name,
            field_names,
            field_types,
            response,
            ..
        } = method;
        quote! {
            #[derive(
                Clone,
                Debug,
                embedded_gpui::serde::Serialize,
                embedded_gpui::serde::Deserialize,
            )]
            #[serde(crate = "embedded_gpui::serde")]
            #vis struct #message_ident {
                #(pub #field_names: #field_types,)*
            }

            impl embedded_gpui::Message for #message_ident {
                type Spec = #spec_ident;
                type Response = #response;
                const METHOD: &'static str = #method_name;
            }
        }
    });

    let event_impls = events.iter().map(|event| {
        let event_name = snake_case(
            &event
                .segments
                .last()
                .map(|segment| segment.ident.to_string())
                .unwrap_or_default(),
        );
        quote! {
            impl embedded_gpui::Event for #event {
                type Spec = #spec_ident;
                const EVENT: &'static str = #event_name;
            }
        }
    });

    // The checked registration functions #[shared] compiles against: the function
    // pointer type is the schema's notion of the method, so a home whose signature
    // drifts fails to compile.
    let register_fns = methods.iter().map(|method| {
        let Method {
            ident,
            message_ident,
            method_name,
            field_names,
            field_types,
            response,
            ref_response: _,
            is_async,
        } = method;
        let register_ident = format_ident!("register_{ident}");
        if *is_async {
            quote! {
                #[doc(hidden)]
                pub fn #register_ident<T: 'static>(
                    methods: &mut embedded_gpui::Methods<#spec_ident, T>,
                    handler: fn(
                        &mut T,
                        #(#field_types,)*
                        &mut embedded_gpui::gpui::Context<T>,
                    ) -> embedded_gpui::gpui::Task<embedded_gpui::anyhow::Result<#response>>,
                ) {
                    methods.on_async(#method_name, move |entity, _method, payload, cx| {
                        let task = (|| {
                            let message: #message_ident = embedded_gpui::decode(payload)?;
                            embedded_gpui::anyhow::Ok(entity.update(cx, |this, cx| {
                                handler(this, #(message.#field_names,)* cx)
                            }))
                        })();
                        match task {
                            Ok(task) => cx.spawn(async move |_| {
                                let response = task.await?;
                                embedded_gpui::encode(&response)
                            }),
                            Err(error) => embedded_gpui::gpui::Task::ready(Err(error)),
                        }
                    });
                }
            }
        } else {
            quote! {
                #[doc(hidden)]
                pub fn #register_ident<T: 'static>(
                    methods: &mut embedded_gpui::Methods<#spec_ident, T>,
                    handler: fn(
                        &mut T,
                        #(#field_types,)*
                        &mut embedded_gpui::gpui::Context<T>,
                    ) -> #response,
                ) {
                    methods.on(#method_name, move |entity, _method, payload, cx| {
                        let message: #message_ident = embedded_gpui::decode(payload)?;
                        let response = entity.update(cx, |this, cx| {
                            handler(this, #(message.#field_names,)* cx)
                        });
                        embedded_gpui::encode(&response)
                    });
                }
            }
        }
    });

    let event_bounds = events.iter().map(|event| {
        let bound: syn::WherePredicate =
            syn::parse_quote!(T: embedded_gpui::gpui::EventEmitter<#event>);
        bound
    });
    let event_forwarders = events.iter().map(|event| {
        quote! {
            subscriptions.push(cx.subscribe(entity, {
                let sink = sink.clone();
                move |_, event: &#event, cx| match embedded_gpui::encode(event) {
                    Ok(payload) => sink(
                        <#event as embedded_gpui::Event>::EVENT,
                        payload,
                        cx,
                    ),
                    Err(error) => embedded_gpui::log::error!(
                        "embedded_gpui: failed to encode shared event: {error:#}"
                    ),
                }
            }));
        }
    });

    let caller_ident = format_ident!("{spec_ident}Caller");
    let caller_signatures = methods.iter().map(|method| {
        let Method {
            ident,
            field_names,
            field_types,
            response,
            ref_response,
            ..
        } = method;
        let receipt_of = match ref_response {
            Some(inner) => quote!(embedded_gpui::Remote<#inner>),
            None => quote!(#response),
        };
        quote! {
            fn #ident(
                &self,
                #(#field_names: #field_types,)*
                cx: &mut embedded_gpui::gpui::App,
            ) -> embedded_gpui::Receipt<#receipt_of>;
        }
    });
    let caller_implementations = methods.iter().map(|method| {
        let Method {
            ident,
            message_ident,
            field_names,
            field_types,
            response,
            ref_response,
            ..
        } = method;
        match ref_response {
            // A ref-returning method resolves with a live, connected Remote: object
            // allocation across the boundary, handle in, handle out.
            Some(inner) => quote! {
                fn #ident(
                    &self,
                    #(#field_names: #field_types,)*
                    cx: &mut embedded_gpui::gpui::App,
                ) -> embedded_gpui::Receipt<embedded_gpui::Remote<#inner>> {
                    self.call_connecting(#message_ident { #(#field_names,)* }, cx)
                }
            },
            None => quote! {
                fn #ident(
                    &self,
                    #(#field_names: #field_types,)*
                    cx: &mut embedded_gpui::gpui::App,
                ) -> embedded_gpui::Receipt<#response> {
                    self.call(#message_ident { #(#field_names,)* }, cx)
                }
            },
        }
    });

    let spec_doc = format!(
        "\n\nThe `{spec_ident}` interface: hold one as `Remote<{spec_ident}>`, \
         reference one as `Ref<{spec_ident}>`, implement one with \
         `#[shared] impl {spec_ident} for ...`."
    );
    let caller_doc = format!(
        "Typed calls to a shared `{spec_ident}` entity: implemented for \
         `Remote<{spec_ident}>`, one method per interface method, each returning a \
         `Receipt`. Methods declared to return `Ref<T>` resolve with a connected \
         `Remote<T>` instead: allocation over there, handle over here."
    );

    Ok(quote! {
        #(#doc_attrs)*
        #[doc = #spec_doc]
        #vis struct #spec_ident;

        impl embedded_gpui::Interface for #spec_ident {
            const TYPE_NAME: &'static str = #type_name;
        }

        impl #spec_ident {
            #(#register_fns)*

            #[doc(hidden)]
            #[allow(unused_variables, unused_mut)]
            pub fn wire_events<T>(
                entity: &embedded_gpui::gpui::Entity<T>,
                sink: embedded_gpui::EventSink,
                cx: &mut embedded_gpui::gpui::App,
            ) -> Vec<embedded_gpui::gpui::Subscription>
            where
                T: 'static,
                #(#event_bounds,)*
            {
                let mut subscriptions = Vec::new();
                #(#event_forwarders)*
                subscriptions
            }
        }

        #(#message_items)*

        #(#event_impls)*

        #[doc = #caller_doc]
        #vis trait #caller_ident {
            #(#caller_signatures)*
        }

        impl #caller_ident for embedded_gpui::Remote<#spec_ident> {
            #(#caller_implementations)*
        }
    })
}

fn expand_home(mut item_impl: ItemImpl) -> syn::Result<proc_macro2::TokenStream> {
    let Some((None, spec_path, _for_token)) = item_impl.trait_.clone() else {
        return Err(syn::Error::new(
            item_impl.span(),
            "#[shared] goes on `impl SomeInterface for SomeEntity { ... }`",
        ));
    };
    // The methods become ordinary (inherent) methods of the entity; the interface name
    // is only used to find the schema's registration functions.
    item_impl.trait_ = None;

    let mut registrations = Vec::new();
    for item in &item_impl.items {
        let syn::ImplItem::Fn(function) = item else {
            continue;
        };
        let ident = &function.sig.ident;
        let register_ident = format_ident!("register_{ident}");
        registrations.push(quote! {
            #spec_path::#register_ident::<Self>(methods, Self::#ident);
        });
    }

    let self_ty = item_impl.self_ty.clone();
    let (impl_generics, _, where_clause) = item_impl.generics.split_for_impl();

    Ok(quote! {
        #item_impl

        impl #impl_generics embedded_gpui::Shared<#spec_path> for #self_ty #where_clause {
            fn methods(methods: &mut embedded_gpui::Methods<#spec_path, Self>) {
                #(#registrations)*
            }

            fn events(
                entity: &embedded_gpui::gpui::Entity<Self>,
                sink: embedded_gpui::EventSink,
                cx: &mut embedded_gpui::gpui::App,
            ) -> Vec<embedded_gpui::gpui::Subscription> {
                #spec_path::wire_events::<Self>(entity, sink, cx)
            }
        }
    })
}

fn pascal_case(snake: &str) -> String {
    snake
        .split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn snake_case(pascal: &str) -> String {
    let mut out = String::new();
    for (index, ch) in pascal.chars().enumerate() {
        if ch.is_uppercase() {
            if index > 0 {
                out.push('_');
            }
            out.extend(ch.to_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}
